theme = "solarized-dark"
icons = "awesome"

# [[block]]
# block = "music"
# player = "spotify"
# buttons = ["play", "next"]

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/viv/Mail/Inbox"]
threshold_warning = 1
threshold_critical = 10

[[block]]
block = "time"
interval = 60
format = "%a %b %d %R"