theme = "solarized-dark"
icons = "awesome"

# [[block]]
# block = "music"
# player = "spotify"
# buttons = ["play", "next"]
# max_width = 24

[[block]]
block = "memory"
display_type = "memory"
clickable = false
format_mem = "{MAg} GiB"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/viv/Mail/fastmail/Inbox"]
threshold_warning = 1
threshold_critical = 10

[[block]]
block = "net"
device = "wlan0"
ssid = true
bitrate = true
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "wwp0s20f0u6"
ip = false
bitrate = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
ip = true
bitrate = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %b %d %R"